# -*- coding: utf-8 -*-
"""Stocks_code.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1x896lhi9KwX9JZwLTP5mXGbhjtWHKIjT
"""

import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
from tkinter import Tk, filedialog, messagebox

def load_data():
    # Create a Tkinter window
    root = Tk()
    root.withdraw()  # Hide the main window
    
    # Ask the user to select a file
    file_path = filedialog.askopenfilename(filetypes=[("CSV files", "*.csv")])
    
    if file_path:
        try:
            # Load the CSV file
            dataset_train = pd.read_csv(file_path)
            
            # Data preprocessing steps
            # For demonstration, I'll print the shape and head of the loaded dataset
            print('Shape of dataset: {}'.format(dataset_train.shape))
            print(dataset_train.head())
            
            # Extracting the relevant training data
            training_set = dataset_train.iloc[:, 1:2].values
            
            # Visualizing the data (just a basic plot as an example)
            plt.plot(training_set, color='red', label='Google Stock Price in Training set')
            plt.xlabel('Time')
            plt.ylabel('Google Stock Price')
            plt.legend()
            plt.show()
            
        except Exception as e:
            messagebox.showerror("Error", str(e))
    else:
        messagebox.showwarning("Warning", "No file selected.")

if __name__ == '__main__':
    load_data()
