# -*- coding: utf-8 -*-
"""Stocks_code_with_login.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1x896lhi9KwX9JZwLTP5mXGbhjtWHKIjT
"""

import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
from tkinter import Tk, filedialog, messagebox, Label, Entry, Button, StringVar

# Hardcoded credentials for demonstration (you should use a more secure method in practice)
VALID_USERNAME = "admin"
VALID_PASSWORD = "password123"

class LoginWindow:
    def __init__(self, root):
        self.root = root
        self.root.title("Login")
        
        self.username_label = Label(root, text="Username:")
        self.username_label.pack()
        
        self.username_entry = Entry(root)
        self.username_entry.pack()
        
        self.password_label = Label(root, text="Password:")
        self.password_label.pack()
        
        self.password_entry = Entry(root, show="*")
        self.password_entry.pack()
        
        self.login_button = Button(root, text="Login", command=self.login)
        self.login_button.pack()
        
        self.message_label = Label(root, text="")
        self.message_label.pack()
    
    def login(self):
        username = self.username_entry.get()
        password = self.password_entry.get()
        
        if username == VALID_USERNAME and password == VALID_PASSWORD:
            self.message_label.config(text="Login successful!", fg="green")
            self.open_file_dialog()
        else:
            self.message_label.config(text="Invalid username or password", fg="red")
    
    def open_file_dialog(self):
        self.root.withdraw()  # Hide login window
        
        # Create a Tkinter window for file selection
        file_path = filedialog.askopenfilename(filetypes=[("CSV files", "*.csv")])
        
        if file_path:
            try:
                # Load the CSV file
                dataset_train = pd.read_csv(file_path)
                
                # Data preprocessing steps
                # For demonstration, I'll print the shape and head of the loaded dataset
                print('Shape of dataset: {}'.format(dataset_train.shape))
                print(dataset_train.head())
                
                # Extracting the relevant training data
                training_set = dataset_train.iloc[:, 1:2].values
                
                # Visualizing the data (just a basic plot as an example)
                plt.plot(training_set, color='red', label='Google Stock Price in Training set')
                plt.xlabel('Time')
                plt.ylabel('Google Stock Price')
                plt.legend()
                plt.show()
                
            except Exception as e:
                messagebox.showerror("Error", str(e))
        else:
            messagebox.showwarning("Warning", "No file selected.")
        
        self.root.destroy()  # Close the application after file selection

def main():
    root = Tk()
    login_window = LoginWindow(root)
    root.mainloop()

if __name__ == '__main__':
    main()
